---
os: linux
dist: bionic

language: python
python:
  - "3.8"

env:
  global:
    - BUILDER: packer
    - BUILDER_VERSION: 1.6.0
    - OS_ARCH: linux_amd64
  jobs:
    # - BOX: ubuntu-2004
    - BOX: ubuntu-1804
    # - BOX: ubuntu-1604
    - BOX: debian-10
    - BOX: debian-9
    - BOX: centos-7


before_install:
  - sudo apt-get update
  - sudo apt-get install wget unzip software-properties-common linux-headers-$(uname -r) -y

install:
  - echo -e "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install virtualbox-6.1 -y
  - sudo /sbin/vboxconfig


before_script:
  - wget -v -O vagrant.zip https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_${OS_ARCH}.zip
  - sudo unzip vagrant.zip -d /usr/local/bin
  - wget -v -O ${BUILDER}.zip https://releases.hashicorp.com/${BUILDER}/${BUILDER_VERSION}/${BUILDER}_${BUILDER_VERSION}_${OS_ARCH}.zip
  - unzip $BUILDER.zip -d .

script:
  - sudo ./$BUILDER --version
  - sudo ./ci-support.sh
